I"Ì<p>UPDATE: NVM.Â https://www.onshape.com/featurescript Use the gear generator feature. Itâ€™s in the plus sign at the right hand side of the menu bar.</p>

<p>You can make stacked gears using the union function to make the pieces of a differential gear train</p>

<hr />

<p>Wanted to make some gears. Could use openscad but not super comfortable with it and I kind of donâ€™t like how the gear library draws the gears.</p>

<p>https://www.youtube.com/watch?v=TgihDwr7Mmw</p>

<p>This seemed pretty good. However, using circular arcs for the gear teeth is not correct. They are involute curves, curves traced out by</p>

<p>Some good resource books are Shigleyâ€™s Mechanical Engineering Design, Machinery Handbook and these sites</p>

<p><a href="https://www.cs.cmu.edu/~rapidproto/mechanisms/chpt7.html">https://www.cs.cmu.edu/~rapidproto/mechanisms/chpt7.html</a></p>

<p><a href="http://www.gearseds.com/files/Approx_method_draw_involute_tooth_rev2.pdf">http://www.gearseds.com/files/Approx_method_draw_involute_tooth_rev2.pdf</a></p>

<p>A list of some terminology:</p>

<p>The pitch point is the point of contact between two gears that lies between their centers.</p>

<p>The pitch diameter is how far that point will be from the center of the gear. This tells you how far apart to mount the two gears</p>

<p>The diametral pitch is the number of teeth divided by the pitch diameter. What horrible terminology. It must have units of inverse inches typically. P * D Â = N</p>

<p>The circular pitch p is the distance between the same point on each tooth . $ p P = \pi$</p>

<p>At the height of the pitch circle there is just as much tooth as tooth gap.</p>

<p>pressure angle is the angle between tooth profile and diameter at the pitch point.</p>

<p>If two gears have the same diametral pitch and Â pressure angle (and appropriate tooth profiles) theyâ€™ll mesh.</p>

<p>For a rack, the teeth are straight lines with the pressure angle with respect to the normal.</p>

<p>For full cut teeth</p>

<p>the outer diameter is Pitch Diameter + 2/P =</p>

<p>the root diameter is Pitch Diameter - 2/P =</p>

<p>For a rack, itâ€™s much easier to work with p</p>

<p>Top of tooth is 1/P = p / $ \pi$</p>

<p>the root diameter is Pitch Diameter - 1/P =</p>

<p>Onshape instructions:</p>

<p>So make sketch. Draw the root circle, pitch circle, and outer diameter circle.</p>

<p>Now we need to find the base circle, the circle from which the involute is unrolled. Make a radial line. Make a perpendicular to that line touching the pitch circle. Make another radial line at the pressure angle from the first. Make a line at the pressure angle from the pitch perpendicular Â you drew. These two lines should intersect at 90 degrees. That point lies on the base circle. Make a circle that touches that point.</p>

<p>Now the involute. I decided to go with a spline. Write down the radius of the base circle. Make a radial and a perpendicular to that radial and tangent to the base circle.</p>

<p>Make the same thing a couple of times at intervals of 10 degrees or something. Now, set the length of each of the perpendiculars to the arc length away from the first point, i.e. 10<em>pi/90 * B, 20</em>pi/90 * B, 30*pi/90 * B, â€¦ where B is the diameter of the Base circle. Now draw a spline connecting the ends of all these lines. This is a good involute. You can stop when the involute crosses the outer diameter.</p>

<p>Draw a radial to the point where the involute touches the pitch circle. Draw another radial at 360/N/4 degrees away from that point where N is number of teethon the concave side of the involute. Now reflect the involute over this line. You have the other side of this tooth</p>

<p>Draw radials to connect to the root circle and a cap line or arc at the outer diameter.</p>

<p>Now extrude. Use some reasonable fillets on the ends and roots of the teeth. Use circular pattern to make the rest of the teeth.</p>

<p>For a rack, draw three horizontal lines at with spacing 1/P. Draw up from the root line a line at the pressure angle from the vertical. Mark where it crosses pitch line. Make a vertical line p/4 (circular pitch) away from it and reflect the line over it. Close off the top. This is a tooth.</p>

<p>Extrude, fillet, and make a linear pattern.</p>

<p>There ya go.</p>

:ET